{% set name = "flake8-functions-names" %}
{% set version = "0.3.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/flake8_functions_names-{{ version }}.tar.gz
  sha256: 1a86ad60a04ce8dbe5af10275eaf56e2a3c23884f88e103f9fac5489d0435b81

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - python >=3.8
    - setuptools

test:
  imports:
    - flake8_functions_names
    - flake8_functions_names.utils
  commands:
    - pip check
    - flake8 --version | grep flake8-functions-names
  requires:
    - flake8
    - m2-grep  # [win]
    - pip

about:
  home: https://github.com/Melevir/flake8-functions-names
  summary: An extension for flake8 that validates functions names, decomposition and conformity with annotations.
  license: MIT
  # PR Made upstream to package in license file: https://github.com/Melevir/flake8-functions-names/pull/11
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
